### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'default'

### ISSUE THREAD

**Issue by dimdenGD** [vadimkorr/svelte-carousel#134]
I get error in the title when trying to use it like this in SvelteKit 1.5.0:
```
TypeError: Cannot read properties of undefined (reading 'default')
    at Module.createCarousel [as default] (/node_modules/svelte-carousel/src/components/Carousel/createCarousel.js:23:19)
    at Carousel.svelte:33:70
    at Object.$$render (/node_modules/svelte/internal/index.mjs:1892:22)
    at eval (/src/routes/+page.svelte:52:99)
    at Object.$$render (/node_modules/svelte/internal/index.mjs:1892:22)
    at Object.default (root.svelte:42:40)
    at eval (/src/routes/+layout.svelte:48:32)
    at Object.$$render (/node_modules/svelte/internal/index.mjs:1892:22)
    at root.svelte:41:39
    at $$render (/node_modules/svelte/internal/index.mjs:1892:22)
```

using code:

```svelte
<script>
    import Carousel from 'svelte-carousel';
</script>
<div>
    <Carousel>
        <div>test</div>
        <div>test</div>
    </Carousel>
</div>
```

Versions:
    "@sveltejs/adapter-auto": "^2.0.0",
    "@sveltejs/kit": "^1.5.0",
    "svelte": "^3.54.0",
    "svelte-carousel": "^1.0.23",
    "vite": "^4.0.0"

**Comment by MelleNi** [comment]
Same issue

**Comment by Jaydeep189** [comment]
Getting th exact same error

**Comment by TomixUG** [comment]
Same

**Comment by frandevea** [comment]
same issue

**Comment by g-roll** [comment]
With the [browser module](https://kit.svelte.dev/docs/modules#$app-environment-browser) you can run code client-side only.

```svelte
<script>
	import { browser } from '$app/environment';
	import Carousel from 'svelte-carousel';

	export let testimonials;
</script>

{#if browser}
	<Carousel>
		{#each testimonials as testimonial}
			...
		{/each}
	</Carousel>
{/if}

```

Works for me in SvelteKit v1.20.4

**Comment by niocncn** [comment]
same issue on svelte 4
