### ISSUE TITLE
failing on import ... any ideas?

### ISSUE THREAD

**Issue by aktxyz** [vadimkorr/svelte-carousel#27]
```
<script>
    import Carousel from "svelte-carousel";
</script>

Cannot use import statement outside a module
C:\...\app\node_modules\svelte-carousel\src\main.js:1
import Carousel from './components/Carousel/Carousel.svelte'

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:984:16)
    at Module._compile (internal/modules/cjs/loader.js:1032:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at nodeRequire (C:\...\app\node_modules\vite\dist\node\chunks\dep-e9a16784.js:68211:17)
    at ssrImport (C:\...\app\node_modules\vite\dist\node\chunks\dep-e9a16784.js:68164:20)
    at eval (/src/embed/calc/CalcMortgagePayment.svelte:7:31)
```

**Comment by tonprince** [comment]
I had the same issue when using within Sveltekit.

**Comment by aktxyz** [comment]
ah, sveltekit related ... that's a decent clue !

**Comment by vadimkorr** [comment]
The official workaround is:
1. Install it as a dev dependency:
`npm install svelte-carousel -D`

2. Import it like this: 
```
<script>
  import { onMount } from 'svelte';

  let Carousel;
  onMount(async () => {
    const module = await import('svelte-carousel');
    Carousel = module.default;
  });
</script>

<svelte:component this={Carousel}>
  <div>1</div>
  <div>2</div>
  <div>3</div>
</svelte:component>
```


[How do I use a client-side only library that depends on document or window?](https://kit.svelte.dev/faq)
[why -D ?](https://github.com/sveltejs/sapper-template#using-external-components)

**Comment by aktxyz** [comment]
fantastic ... thanks !

**Comment by tonprince** [comment]
Thanks, that is great.

**Comment by OClement** [comment]
FYI: This issue is back on 1.0.17-rc4 (latest as of this writing)
Downgrading to 1.0.16 and using the workwaround [above](https://github.com/vadimkorr/svelte-carousel/issues/27#issuecomment-851022295) still works

**Comment by cloudlena** [comment]
Somehow, the workaround renders an error with the new `svelte-check@3`:

```txt
Error: Argument of type 'SvelteComponentDev' is not assignable to parameter of type 'ConstructorOfATypedSvelteComponent'.
  Type 'SvelteComponentDev' provides no match for the signature 'new (args: { target: any; props?: any; }): ATypedSvelteComponent'.

Possible causes:
- You use the instance type of a component where you should use the constructor type
- Type definitions are missing for this Svelte Component. If you are using Svelte 3.31+, use SvelteComponentTyped to add a definition:
  import type { SvelteComponentTyped } from "svelte";
  class ComponentName extends SvelteComponentTyped<{propertyName: string;}> {} (ts)
                        <div class="container">
                                <svelte:component this={Carousel} particlesToShow={3} autoplay={true} dots={false}>
                                        {#each techs as tech (tech.name)}
```

The source code can be found here: https://github.com/bespinian/bespinian.io/blob/main/src/routes/Tech.svelte#L11
