### ISSUE TITLE
Not working with Sveltekit (without onMount import workaround)

### ISSUE THREAD

**Issue by brentmparker** [vadimkorr/svelte-carousel#40]
Using `import Carousel from 'svelte-carousel'` causes the following error in Sveltekit:

```
Cannot use import statement outside a module

local\path\on\my\machine\node_modules\svelte-carousel\src\main.js:1
import Carousel from './components/Carousel/Carousel.svelte'
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1025:15)
    at Module._compile (node:internal/modules/cjs/loader:1059:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:816:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at nodeRequire (E:\Development\Web\komputiko\frontend\node_modules\vite\dist\node\chunks\dep-fc2895ac.js:72504:17)
    at ssrImport (E:\Development\Web\komputiko\frontend\node_modules\vite\dist\node\chunks\dep-fc2895ac.js:72457:20)
    
```
    
    
package.json does not contain "type": "module"

Making this work may require more than adding that to package.json, but I'm not familiar enough with npm packages to know for sure.

There is a workaround, but it's not very pretty.
Instead of importing at the top of the file, imports must be delayed until onMount:

```
let Carousel;
onMount(async () => {
	const module = await import('svelte-carousel');
	Carousel = module.default;
});
```

And in your markup use

```
<svelte:component this={Carousel}>
...
</svelte:component>
```

**Comment by vadimkorr** [comment]
This is known behaviour for packages which use `window` in SSR. Please take a look at the following issue, there are links with explanations.
Duplicate https://github.com/vadimkorr/svelte-carousel/issues/27

**Comment by brentmparker** [comment]
My mistake. Thanks for the reference. Closing this issue.
