### ISSUE TITLE
No loader is configured for ".svelte" files using adapter-cloudflare-workers

### ISSUE THREAD

**Issue by lynchem** [vadimkorr/svelte-carousel#66]
I had the Carousel working nicely using the static adapter and the onMount import workaround listed here, but when I switched to using the cloudflare-workers adapter it gives this error: 

```
> Using @sveltejs/adapter-cloudflare-workers
 > node_modules/svelte-carousel/src/main.js:1:21: error: No loader is configured for ".svelte" files: node_modules/svelte-carousel/src/components/Carousel/Carousel.svelte
    1 │ import Carousel from './components/Carousel/Carousel.svelte'
      ╵                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

> Build failed with 1 error:
node_modules/svelte-carousel/src/main.js:1:21: error: No loader is configured for ".svelte" files: node_modules/svelte-carousel/src/components/Carousel/Carousel.svelte
Error: Build failed with 1 error:
node_modules/svelte-carousel/src/main.js:1:21: error: No loader is configured for ".svelte" files: node_modules/svelte-carousel/src/components/Carousel/Carousel.svelte
    at failureErrorWithLog (/home/mark/dev/sonas-web/node_modules/esbuild/lib/main.js:1449:15)
    at /home/mark/dev/sonas-web/node_modules/esbuild/lib/main.js:1131:28
    at runOnEndCallbacks (/home/mark/dev/sonas-web/node_modules/esbuild/lib/main.js:1049:65)
    at buildResponseToResult (/home/mark/dev/sonas-web/node_modules/esbuild/lib/main.js:1129:7)
    at /home/mark/dev/sonas-web/node_modules/esbuild/lib/main.js:1236:14
    at /home/mark/dev/sonas-web/node_modules/esbuild/lib/main.js:609:9
    at handleIncomingPacket (/home/mark/dev/sonas-web/node_modules/esbuild/lib/main.js:706:9)
    at Socket.readFromStdout (/home/mark/dev/sonas-web/node_modules/esbuild/lib/main.js:576:7)
    at Socket.emit (events.js:375:28)
    at Socket.emit (domain.js:470:12)
```

Any ideas ?

**Comment by Twijgjes** [comment]
Maybe check your `webpack.config.js`. I had the node_modules excluded in the svelte-loader configuration. Removing the exclusion `exclude: /(node_modules)/` fixed this issue for me. You can find a "plain" svelte-loader webpack config here:
https://github.com/sveltejs/svelte-loader
